### PR TITLE
add logger and fix bug issue #19

### LINKED ISSUE #19: Command stops in the middle if someone already has a role
We execute `bqiam permit project READER -u user1 -u user2 -u, ...`, but when some already has a role `roles/viewer` in the project, the command stops in the middle.

### PR DESCRIPTION
**Pull request by hirosassa**
# What is this PR?

fix #19 and #3 

I also introduce `zerolog` for verbose outputs

### usage
```bash 
$ bqiam permit project READER -p sample-project-id -u use@example.com -v // added verbose option flag
project_id: sample-project-id
role:       roles/viewer
users:      [use@example.com]
If you proceeds, PROJECT-WIDE permission will be added. Are you sure? [y/n]y
{"level":"info","time":"2020-09-05T16:00:45+09:00","message":"use@example.com already has a role: roles/viewer, project: sample-project-id. skipped."}. // This is a verbose output.
Permit  use@example.com to sample-project-id access as roles/viewer
```

### CODE REVIEW

File: bqrole/project.go [hunk 1]
```diff
@@ -63,8 +64,9 @@ func grantProjectRole(project, user, role string) error {
 		return fmt.Errorf("failed to fetch current policy: error %s", err)
 	}
 
-	if hasProjectRole(*policy, user, role) {
-		return fmt.Errorf("%s already has a role: %s, project: %s", user, role, project)
```
Comment (hirosassa) [inline bqrole/project.go:67]: This is why a process stops in the middle. Fix it by returns nil and log the event.

File: cmd/root.go [hunk 2]
```diff
@@ -72,6 +87,11 @@ func init() {
 	rootCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
 
 	rootCmd.PersistentFlags().IntP("refresh", "r", 24, "cache refresh threshold in hour (default is 24 hours)")
+
+	// for log output
+	rootCmd.PersistentFlags().BoolVarP(&verbose, "verbose", "v", false, "enable varbose log output")
+	rootCmd.PersistentFlags().BoolVar(&debug, "debug", false, "enable debug log output")
```
Comment (hirosassa) [inline cmd/root.go:93]: parse flags for log output

File: cmd/root.go [hunk 3]
```diff
@@ -64,6 +67,18 @@ func initConfig() {
...
+
+func logOutput() {
+	zerolog.SetGlobalLevel(zerolog.Disabled) // default: quiet mode
+	switch {
+	case verbose:
+		zerolog.SetGlobalLevel(zerolog.InfoLevel)
+	case debug:
+		zerolog.SetGlobalLevel(zerolog.DebugLevel)
+	}
 }
```
Comment (hirosassa) [inline cmd/root.go:82]: set log levels

File: cmd/root.go [hunk 4]
```diff
@@ -5,6 +5,7 @@ import (
 	"os"
 
 	homedir "github.com/mitchellh/go-homedir"
+	"github.com/rs/zerolog"
```
Comment (hirosassa) [inline cmd/root.go:8]: introduce `zerolog`

File: go.mod [hunk 5]
```diff
@@ -1,6 +1,6 @@
 module github.com/hirosassa/bqiam
 
-go 1.14
+go 1.15
```
Comment (hirosassa) [inline go.mod:3]: update go version

**Comment by hirosassa** [comment]
@snowhork Plz review!

**Comment by snowhork** [comment]
@hirosassa LGTM! thanks!

**Comment by hirosassa** [comment]
@snowhork Thanks!

**Comment by hirosassa** [comment]
also fixed #3
